---
# JetBrains Toolbox Role - Default Variables

# Enable/disable JetBrains Toolbox installation
jetbrains_enabled: true

# JetBrains Toolbox version
jetbrains_toolbox_version: "2.1.3.18901"
jetbrains_toolbox_url: "https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz"

# Installation directory
jetbrains_toolbox_install_dir: "{{ ansible_env.HOME }}/.local/share/JetBrains/Toolbox"

# Create desktop entry
jetbrains_create_desktop_entry: true
