---
galaxy_info:
  author: nezael
  description: JetBrains Toolbox for managing PhpStorm, DataGrip, and other IDEs
  license: MIT
  min_ansible_version: "2.17"
  platforms:
    - name: Archlinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies: []
